FROM node:22-alpine3.20 AS dev
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
EXPOSE 3030
CMD ["pnpm", "dev", "--host", "0.0.0.0"]
