bitecode:
  document:
    storage:
      default-storage-type: ${BITECODE_DOCUMENT_STORAGE_DEFAULT_STORAGE_TYPE:LOCAL}
      local:
        base-path: ${BITECODE_DOCUMENT_STORAGE_LOCAL_BASE_PATH:./storage/documents}
      s3:
        bucket: ${BITECODE_DOCUMENT_STORAGE_S3_BUCKET:}
        region: ${BITECODE_DOCUMENT_STORAGE_S3_REGION:us-east-1}
        endpoint: ${BITECODE_DOCUMENT_STORAGE_S3_ENDPOINT:}
        access-key: ${BITECODE_DOCUMENT_STORAGE_S3_ACCESS_KEY:}
        secret-key: ${BITECODE_DOCUMENT_STORAGE_S3_SECRET_KEY:}
        force-path-style: ${BITECODE_DOCUMENT_STORAGE_S3_FORCE_PATH_STYLE:true}
